### ISSUE TITLE
Errno::EINVAL: Invalid argument instead of Redis::CannotConnectError

### ISSUE THREAD

**Issue by printercu** [redis/hiredis-rb#21]
Sometimes this code fails (on different iteration) with `Errno::EINVAL: Invalid argument` when redis server is down.

``` ruby
redis = Redis.new(driver: :hiredis)
10000.times do |i|
  puts(i.to_s)
  begin
    redis.get(1)
  rescue Redis::CannotConnectError
  end
end
# oneliner:
# redis = Redis.new(driver: :hiredis); 10000.times { |i| puts(i.to_s); begin; redis.get(1); rescue Redis::CannotConnectError; end }
```

`:ruby` driver is ok.

**Comment by mickey** [comment]
A few of our gems, rescue from `Redis::BaseError` to handle failure (readthis, flipper,...) so with `Errno::EINVAL` in case of failure/failover it fails when it should not.

Here's my patch:
```ruby
class Hiredis::Connection
  def connect_with_decorate_errno_einval(host, port, timeout)
    begin
      connect_without_decorate_errno_einval(host, port, timeout)
    rescue Errno::EINVAL => e
      raise Redis::CannotConnectError, e.message
    end
  end
  alias_method_chain :connect, :decorate_errno_einval
end
```

**Comment by ashiksp** [comment]
Any update on this issue ?

**Comment by mandaputtra** [comment]
Hi, got this message too any recomendation on solving it? LinuxMint 19.01

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 6379:6379 failed - connect EINVAL 0.0.24.235:6379 - Local (0.0.0.0:0)
    at internalConnect (net.js:881:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:294:19)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1028:9)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:59:10)
Emitted 'error' event at:
    at RedisClient.onError (/home/maxsol/Works/yanmar-nodejs/node_modules/socket.io-redis/index.js:118:12)
    at RedisClient.emit (events.js:198:13)
    at RedisClient.on_error (/home/maxsol/Works/yanmar-nodejs/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/home/maxsol/Works/yanmar-nodejs/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```
